name: "Setup"
description: "Set up the environment"

inputs:
  token:
    description: "A GitHub token."
    required: true
    type: string
  packageManager:
    description: "Package manager to use"
    type: string
    required: false
    default: "yarn"
  skip-build:
    description: "Skip the build step"
    type: string
    required: false
    default: "false"
  php-version:
    description: "PHP version to install on the runner."
    type: string
    required: false
    default: "8.4"


runs:
  using: "composite"
  steps:
    - name: Install svn
      shell: bash
      run: |
        sudo apt install subversion

    - name: Install NodeJS
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".nvmrc"
        cache: ${{ inputs.packageManager }}

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
      with:
        php-version: ${{ inputs.php-version }}
      env:
        COMPOSER_TOKEN: ${{ inputs.token }}

    - name: Install all dependencies (yarn)
      shell: bash
      if: ${{ 'yarn' == inputs.packageManager }}
      run: |
        composer install || composer update wporg/*
        yarn
        yarn setup:tools

    - name: Build all included projects (yarn)
      shell: bash
      if: ${{ inputs.packageManager == 'yarn' && inputs.skip-build != 'true' }}
      run: yarn workspaces run build

    - name: Install all dependencies (npm)
      shell: bash
      if: ${{ 'npm' == inputs.packageManager }}
      run: |
        composer install || composer update wporg/*
        npm install
        npm run setup:tools

    - name: Build all included projects (npm)
      shell: bash
      if: ${{ inputs.packageManager == 'npm' && inputs.skip-build != 'true' }}
      run: npm run build --workspaces --if-present
