/**
 * Flat ESLint config, for ESLint 9+ / `@wordpress/scripts` 32+.
 *
 * Generated by `bin/update-configs`. The rules live in wporg-repo-tools and
 * arrive with `composer update` — edit them there, not here.
 *
 * Project-specific config objects go at the end of the array, after the shared
 * entries, where they override what comes before.
 */

/**
 * Internal dependencies
 */
const createConfig = require( './vendor/wporg/wporg-repo-tools/configs/eslint' );

module.exports = [
	...createConfig( {
		textDomain: '${TEXTDOMAIN}',
		prettierConfig: require( './.prettierrc' ),
	} ),
];
