/**
 * Flat ESLint config, for ESLint 9+ / `@wordpress/scripts` 32+.
 *
 * Generated by `bin/update-configs`. The rules arrive with `composer update` —
 * edit them in wporg-repo-tools, not here. Project-specific config objects go
 * at the end of the array.
 */

/**
 * Internal dependencies
 */
const createConfig = require( './vendor/wporg/wporg-repo-tools/configs/eslint' );

module.exports = [
	...createConfig( {
		textDomain: '${TEXTDOMAIN}',
		prettierConfig: require( './.prettierrc' ),
	} ),
];
