/**
 * Flat ESLint config, for ESLint 9+ / `@wordpress/scripts` 32+.
 *
 * Generated by `bin/update-configs`. The rules live in wporg-repo-tools and
 * arrive with `composer update` — edit them there, not here. Project-specific
 * rules can be appended to the array below.
 */

/**
 * Internal dependencies
 */
const createConfig = require( './vendor/wporg/wporg-repo-tools/configs/eslint' );

module.exports = [ ...createConfig( { textDomain: '${TEXTDOMAIN}' } ) ];
